import _linja1 from './linja_1.json';
import _linja2 from './linja_2.json';
import _linja3 from './linja_3.json';
import _linja4 from './linja_4.json';
import _linja5 from './linja_5.json';
import _linja6 from './linja_6.json';
import _linja7 from './linja_7.json';
import _linja8 from './linja_8.json';
import _linja9 from './linja_9.json';
import _linja10 from './linja_10.json';
import _linja11 from './linja_11.json';
import _linja12 from './linja_12.json';
import _linja13 from './linja_13.json';
import _linja14 from './linja_14.json';
import _linja15 from './linja_15.json';

export const linja1 = _linja1;
export const linja2 = _linja2;
export const linja3 = _linja3;
export const linja4 = _linja4;
export const linja5 = _linja5;
export const linja6 = _linja6;
export const linja7 = _linja7;
export const linja8 = _linja8;
export const linja9 = _linja9;
export const linja10 = _linja10;
export const linja11 = _linja11;
export const linja12 = _linja12;
export const linja13 = _linja13;
export const linja14 = _linja14;
export const linja15 = _linja15;
